import { StyleSheet, Platform, Dimensions } from "react-native";
const maxHeight = Dimensions.get('window').height
const maxWidth = Dimensions.get('window').width


export default StyleSheet.create({

    container: {
        flex: 1,
        backgroundColor: "#FFF"
    },
    flex: { flex: 1 }, 
    colorP: { color: "#73B6FE" },
    colorS: { color: "#5C91CB" },
    colorT: { color: "#BDBDBD" },
    colorW: { color: "#FFF" },
    colorD: { color: "#EB5757" },
    colorB: { color: "#000" },
    colorWarn: { color: "#FFCF4E" },
    colorI: { color: "#28BBD5" },

    bgP: { backgroundColor: "#73B6FE" },
    bgS: { backgroundColor: "#5C91CB" },
    bgT: { backgroundColor: "#BDBDBD" },
    bgW: { backgroundColor: "#FFF" },
    bgB: { backgroundColor: "#000" },
    bgDanger: { backgroundColor: "#EB5757" },
    bgSuccess: { backgroundColor: "#33D37A" },
    bgWarn: { backgroundColor: "#FFCF4E" },
    bgI: { backgroundColor: "#28BBD5" },

    screen_W: { width: maxWidth },
    screen_H: { height: maxHeight },
    /////////////////////////////////
    w_5: { width: "5%", },
    w_10: { width: "10%" },
    w_15: { width: "15%" },
    w_20: { width: "20%" },
    w_25: { width: "25%" },
    w_30: { width: "30%" },
    w_33: { width: "33.33%" },
    w_35: { width: "35%" },
    w_40: { width: "40%" },
    w_45: { width: "45%" },
    w_50: { width: "50%" },
    w_55: { width: "55%" },
    w_60: { width: "60%" },
    w_65: { width: "65%" },
    w_70: { width: "70%" },
    w_75: { width: "75%" },
    w_80: { width: "80%" },
    w_75: { width: "75%" },
    w_90: { width: "90%" },
    w_95: { width: "95%" },
    w_100: { width: "100%" },

    h_5: { height: "5%" },
    h_10: { height: "10%" },
    h_15: { height: "15%" },
    h_20: { height: "20%" },
    h_25: { height: "25%" },
    h_30: { height: "30%" },
    h_35: { height: "35%" },
    h_40: { height: "40%" },
    h_50: { height: "50%" },
    h_55: { height: "55%" },
    h_60: { height: "60%" },
    h_65: { height: "65%" },
    h_70: { height: "70%" },
    h_75: { height: "75%" },
    h_80: { height: "80%" },
    h_75: { height: "75%" },
    h_90: { height: "90%" },
    h_95: { height: "95%" },
    h_100: { height: "100%" },
    /////////////////////////////////

    p5: { padding: 5 },
    p10: { padding: 10 },
    p15: { padding: 15 },
    p20: { padding: 20 },
    p25: { padding: 25 },
    p30: { padding: 30 },
    p35: { padding: 35 },
    p40: { padding: 40 },
    p50: { padding: 50 },
    p60: { padding: 60 },
    p70: { padding: 70 },
    p80: { padding: 80 },
    p90: { padding: 90 },
    p100: { padding: 100 },

    pT5: { paddingTop: 5 },
    pT10: { paddingTop: 10 },
    pT15: { paddingTop: 15 },
    pT20: { paddingTop: 20 },
    pT25: { paddingTop: 25 },
    pT30: { paddingTop: 30 },
    pT35: { paddingTop: 35 },
    pT40: { paddingTop: 40 },
    pT50: { paddingTop: 50 },
    pT60: { paddingTop: 60 },
    pT70: { paddingTop: 70 },
    pT80: { paddingTop: 80 },
    pT90: { paddingTop: 90 },
    pT100: { paddingTop: 100 },

    pB5: { paddingBottom: 5 },
    pB10: { paddingBottom: 10 },
    pB15: { paddingBottom: 15 },
    pB20: { paddingBottom: 20 },
    pB25: { paddingBottom: 25 },
    pB30: { paddingBottom: 30 },
    pB35: { paddingBottom: 35 },
    pB40: { paddingBottom: 40 },
    pB50: { paddingBottom: 50 },
    pB60: { paddingBottom: 60 },
    pB70: { paddingBottom: 70 },
    pB80: { paddingBottom: 80 },
    pB90: { paddingBottom: 90 },
    pB100: { paddingBottom: 100 },

    pL5: { paddingLeft: 5 },
    pL10: { paddingLeft: 10 },
    pL15: { paddingLeft: 15 },
    pL20: { paddingLeft: 20 },
    pL25: { paddingLeft: 25 },
    pL30: { paddingLeft: 30 },
    pL35: { paddingLeft: 35 },
    pL40: { paddingLeft: 40 },
    pL50: { paddingLeft: 50 },
    pL60: { paddingLeft: 60 },
    pL70: { paddingLeft: 70 },
    pL80: { paddingLeft: 80 },
    pL90: { paddingLeft: 90 },
    pL100: { paddingLeft: 100 },

    pR5: { paddingRight: 5 },
    pR10: { paddingRight: 10 },
    pR15: { paddingRight: 15 },
    pR20: { paddingRight: 20 },
    pR25: { paddingRight: 25 },
    pR30: { paddingRight: 30 },
    pR35: { paddingRight: 35 },
    pR40: { paddingRight: 40 },
    pR50: { paddingRight: 50 },
    pR60: { paddingRight: 60 },
    pR70: { paddingRight: 70 },
    pR80: { paddingRight: 80 },
    pR90: { paddingRight: 90 },
    pR100: { paddingRight: 100 },

    pV5: { paddingVertical: 5 },
    pV10: { paddingVertical: 10 },
    pV15: { paddingVertical: 15 },
    pV20: { paddingVertical: 20 },
    pV25: { paddingVertical: 25 },
    pV30: { paddingVertical: 30 },
    pV35: { paddingVertical: 35 },
    pV40: { paddingVertical: 40 },
    pV50: { paddingVertical: 50 },
    pV60: { paddingVertical: 60 },
    pV70: { paddingVertical: 70 },
    pV80: { paddingVertical: 80 },
    pV90: { paddingVertical: 90 },
    pV100: { paddingVertical: 100 },

    pH5: { paddingHorizontal: 5 },
    pH10: { paddingHorizontal: 10 },
    pH15: { paddingHorizontal: 15 },
    pH20: { paddingHorizontal: 20 },
    pH25: { paddingHorizontal: 25 },
    pH30: { paddingHorizontal: 30 },
    pH35: { paddingHorizontal: 35 },
    pH40: { paddingHorizontal: 40 },
    pH50: { paddingHorizontal: 50 },
    pH60: { paddingHorizontal: 60 },
    pV70: { paddingHorizontal: 70 },
    pV80: { paddingHorizontal: 80 },
    pV90: { paddingHorizontal: 90 },
    pH100: { paddingHorizontal: 100 },

    ///////////////////////////////////////////////

    m5: { margin: 5 },
    m10: { margin: 10 },
    m15: { margin: 15 },
    m20: { margin: 20 },
    m25: { margin: 25 },
    m30: { margin: 30 },
    m35: { margin: 35 },
    m40: { margin: 40 },
    m50: { margin: 50 },
    m60: { margin: 60 },
    m70: { margin: 70 },
    m80: { margin: 80 },
    m90: { margin: 90 },
    m100: { margin: 100 },

    mT5: { marginTop: 5 },
    mT10: { marginTop: 10 },
    mT15: { marginTop: 15 },
    mT20: { marginTop: 20 },
    mT25: { marginTop: 25 },
    mT30: { marginTop: 30 },
    mT35: { marginTop: 35 },
    mT40: { marginTop: 40 },
    mT50: { marginTop: 50 },
    mT60: { marginTop: 60 },
    mT70: { marginTop: 70 },
    mT80: { marginTop: 80 },
    mT90: { marginTop: 90 },
    mT100: { marginTop: 100 },

    mB5: { marginBottom: 5 },
    mB10: { marginBottom: 10 },
    mB15: { marginBottom: 15 },
    mB20: { marginBottom: 20 },
    mB25: { marginBottom: 25 },
    mB30: { marginBottom: 30 },
    mB35: { marginBottom: 35 },
    mB40: { marginBottom: 40 },
    mB50: { marginBottom: 50 },
    mB60: { marginBottom: 60 },
    mB70: { marginBottom: 70 },
    mB80: { marginBottom: 80 },
    mB90: { marginBottom: 90 },
    mB100: { marginBottom: 100 },

    mL5: { marginLeft: 5 },
    mL10: { marginLeft: 10 },
    mL15: { marginLeft: 15 },
    mL20: { marginLeft: 20 },
    mL25: { marginLeft: 25 },
    mL30: { marginLeft: 30 },
    mL35: { marginLeft: 35 },
    mL40: { marginLeft: 40 },
    mL50: { marginLeft: 50 },
    mL60: { marginLeft: 60 },
    mL70: { marginLeft: 70 },
    mL80: { marginLeft: 80 },
    mL90: { marginLeft: 90 },
    mL100: { marginLeft: 100 },

    mR5: { marginRight: 5 },
    mR10: { marginRight: 10 },
    mR15: { marginRight: 15 },
    mR20: { marginRight: 20 },
    mR25: { marginRight: 25 },
    mR30: { marginRight: 30 },
    mR35: { marginRight: 35 },
    mR40: { marginRight: 40 },
    mR50: { marginRight: 50 },
    mR60: { marginRight: 60 },
    mR70: { marginRight: 70 },
    mR80: { marginRight: 80 },
    mR90: { marginRight: 90 },
    mR100: { marginRight: 100 },

    mV5: { marginVertical: 5 },
    mV10: { marginVertical: 10 },
    mV15: { marginVertical: 15 },
    mV20: { marginVertical: 20 },
    mV25: { marginVertical: 25 },
    mV30: { marginVertical: 30 },
    mV35: { marginVertical: 35 },
    mV40: { marginVertical: 40 },
    mV50: { marginVertical: 50 },
    mV60: { marginVertical: 60 },
    mV70: { marginVertical: 70 },
    mV80: { marginVertical: 80 },
    mV90: { marginVertical: 90 },
    mV100: { marginVertical: 100 },

    mH5: { marginHorizontal: 5 },
    mH10: { marginHorizontal: 10 },
    mH15: { marginHorizontal: 15 },
    mH20: { marginHorizontal: 20 },
    mH25: { marginHorizontal: 25 },
    mH30: { marginHorizontal: 30 },
    mH35: { marginHorizontal: 35 },
    mH40: { marginHorizontal: 40 },
    mH50: { marginHorizontal: 50 },
    mH60: { marginHorizontal: 60 },
    mV70: { marginHorizontal: 70 },
    mV80: { marginHorizontal: 80 },
    mV90: { marginHorizontal: 90 },
    mH100: { marginHorizontal: 100 },

    ////////////////////////////////////////////

    txAlignC: { textAlign: "center" },
    txAlignJ: { textAlign: "justify" },
    txAlignR: { textAlign: "right" },
    txAlignL: { textAlign: "left" },

    bold: { fontWeight: "bold", },
    bold4: { fontWeight: "400", },
    bold5: { fontWeight: "500", },
    bold6: { fontWeight: "600", },
    bold7: { fontWeight: "700", },
    //   fontFamily:{ fontFamily:'abcd' },

    heading: { fontSize: 28, },

    tx12: { fontSize: 12, fontFamily: 'Poppins-Regular' },
    tx14: { fontSize: 14, fontFamily: 'Poppins-Regular' },
    tx16: { fontSize: 16, fontFamily: 'Poppins-Regular' },
    tx18: { fontSize: 18, fontFamily: 'Poppins-Regular' },
    tx20: { fontSize: 20, fontFamily: 'Poppins-Regular' },
    tx22: { fontSize: 22, fontFamily: 'Poppins-Regular' },
    tx24: { fontSize: 24, fontFamily: 'Poppins-Regular' },
    tx26: { fontSize: 26, fontFamily: 'Poppins-Regular' },
    tx28: { fontSize: 28, fontFamily: 'Poppins-Regular' },
    tx30: { fontSize: 30, fontFamily: 'Poppins-Regular' },

    row: { flexDirection: "row", },
    row_R: { flexDirection: "row-reverse", },
    column: { flexDirection: "column", },
    column_R: { flexDirection: "column-reverse", },

    justify_al_C: { justifyContent: "center", alignItems: "center", },

    justify_C: { justifyContent: "center", },
    justify_A: { justifyContent: "space-around", },
    justify_B: { justifyContent: "space-between", },

    alignI_C: { alignItems: "center", },
    alignI_FE: { alignItems: "flex-end", },
    alignI_FS: { alignItems: "flex-start", },
    alignI_S: { alignItems: "stretch", },

    alignS_C: { alignSelf: "center", },
    alignS_FE: { alignSelf: "flex-end", },
    alignS_FS: { alignSelf: "flex-start", },
    alignS_S: { alignSelf: "stretch", },

    B_colorP: { borderColor: '#E6B363' },
    B_colorS: { borderColor: '#304465' },
    B_colorT: { borderColor: '#BDBDBD' },
    B_colorW: { borderColor: '#FFF' },

    border: { borderWidth: 1 },
    border_B: { borderBottomWidth: 1 },
    border_T: { borderTopWidth: 1 },
    border_L: { borderLeftWidth: 1 },
    border_R: { borderRightWidth: 1 },

    Radius: { borderRadius: 9 },
    // Radius_T: { borderBottomRadius: 10 },
    // Radius_B: { borderTopRadius: 10 },
    // Radius_L: { borderLeftRadius: 10 },
    // Radius_R: { borderRightRadius: 10 },

    Radius_T_L: { borderTopLeftRadius: 10 },
    Radius_T_R: { borderTopRightRadius: 10 },
    Radius_B_L: { borderBottomLeftRadius: 10 },
    Radius_B_R: { borderBottomRightRadius: 10 },

    bordercolor: { borderColor: "#fff" },
    bordercolor_B: { borderBottomColor: "#fff" },
    bordercolor_T: { borderTopColor: "#fff" },
    bordercolor_L: { borderLeftColor: "#fff" },
    bordercolor_R: { borderRightColor: "#fff" },

    border_R: { borderRadius: 10, borderWidth: 1 },


    card0: {
        marginTop: -50,
        backgroundColor: "#ffffff",
        padding: 20,
        borderRadius: 10,
        marginVertical: 10,

        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10.32,
        elevation: 10,
    },
    card1: {
        backgroundColor: "#ffffff",
        paddingVertical: 15,
        paddingHorizontal: 10,
        borderRadius: 10,
        marginHorizontal: 10,
        marginVertical: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10.32,
        elevation: 12,
    },
    card: {
        backgroundColor: "#ffffff",
        padding: 20,
        borderRadius: 10,
        marginHorizontal: 20,
        marginVertical: 10,

        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10.32,
        elevation: 10,
    },
    shadow: {
        borderRadius: 100,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 5,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10.32,
        elevation: 10,
    },
    inputSearch: {
        alignItems: 'center',
        paddingHorizontal: 25,
        marginVertical: 15,
        backgroundColor: '#f1f1f1',
        height: 50,
        borderRadius: 200,
        color: "#73B6FE",
    },
    inputgrey: {
        height: 50,
        paddingLeft: 20,
        borderBottomColor: "#73B6FE",
        borderBottomWidth: 1,
        borderRadius: 5,
        color: "#73B6FE",
    },
    inputred: {
        height: 50,
        paddingLeft: 20,
        borderBottomColor: "red",
        borderBottomWidth: 1,
        borderRadius: 5,
        color: "red",
    },

    inputgrey2: {
        height: 60,
        paddingLeft: 20,
        borderRadius: 100,
        backgroundColor: 'white',
        color: "#FFF",
    },
    inputred2: {
        height: 60,
        paddingLeft: 20,
        borderColor: "red",
        borderWidth: 1,
        backgroundColor: 'white',
        borderRadius: 100,
        color: "red",
    },

});
